name: bitsmedia

services:
  # Audit API (Backend)
  audit-api:
    build:
      context: ../source/audit-api
      dockerfile: ../../orchestrate/audit-api/Dockerfile
    container_name: audit-api
    ports:
      - '5001:5001'
    env_file:
      - audit-api/app.env
    networks:
      - audit-network
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    healthcheck:
      test: ['CMD', 'wget', '--spider', '--quiet', 'http://127.0.0.1:5001/health']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  # Audit UI (Frontend)
  audit-ui:
    build:
      context: ../source/audit-ui
      dockerfile: ../../orchestrate/audit-ui/Dockerfile
      args:
        PUBLIC_API_URL: http://localhost:5001
        PUBLIC_WS_URL: ws://localhost:5001/ws
    container_name: audit-ui
    ports:
      - '4321:4321'
    env_file:
      - audit-ui/app.env
    depends_on:
      audit-api:
        condition: service_healthy
    networks:
      - audit-network
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped

  # Simulator (Worker)
  simulator:
    build:
      context: ../source/simulator
      dockerfile: ../../orchestrate/simulator/Dockerfile
    container_name: simulator
    env_file:
      - simulator/app.env
    depends_on:
      audit-api:
        condition: service_healthy
    networks:
      - audit-network
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped

networks:
  audit-network:
    driver: bridge
