services:
  # Audit API (Backend)
  audit-api:
    build:
      context: ../source/audit-api
      dockerfile: ../../orchestrate/audit-api/Dockerfile
    container_name: audit-api
    ports:
      - "3000:3000"
    env_file:
      - audit-api/app.env
    networks:
      - audit-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  # Audit UI (Frontend)
  audit-ui:
    build:
      context: ../source/audit-ui
      dockerfile: ../../orchestrate/audit-ui/Dockerfile
    container_name: audit-ui
    ports:
      - "4321:4321"
    env_file:
      - audit-ui/app.env
    depends_on:
      audit-api:
        condition: service_healthy
    networks:
      - audit-network
    restart: unless-stopped

  # Simulator (Worker)
  simulator:
    build:
      context: ../source/simulator
      dockerfile: ../../orchestrate/simulator/Dockerfile
    container_name: simulator
    env_file:
      - simulator/app.env
    depends_on:
      audit-api:
        condition: service_healthy
    networks:
      - audit-network
    restart: unless-stopped

networks:
  audit-network:
    driver: bridge
